
[build-system]
requires = ["setuptools >= 70"]
build-backend = "setuptools.build_meta"

[project]
name = "ligotools"
authors = [
  {name = "Ligo Scientific Collaboration (LSC)" },
  { name="Keval Amin", email="keval.amin@berkeley.edu" },
]
description = "LIGO packages for HW3"
readme = "README.md"

requires-python = ">=3.9"
dependencies = [
  "numpy>=2.0",
  "scipy>=1.13",
  "matplotlib>=3.9",
  "h5py>=3.12",
  "ipykernel>=6.29"
]

license = "BSD-3-Clause"
license-files = ["LICEN[CS]E*"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent"
]

keywords = ["LIGO", "gravitational waves", "data analysis", "stat159"]
dynamic = ["version"]



[project.urls]
Homepage = "https://github.com/UCB-stat-159-f25/hw3-kxvlar"
Issues = "https://github.com/UCB-stat-159-f25/hw3-kxvlar/issues"

[tool.setuptools]
packages = ["ligotools"]

[tool.setuptools.dynamic]
version = {attr = "ligotools.__version__"}
